### ISSUE TITLE
arm64 support for focal

### ISSUE THREAD

**Issue by ElectrodeYT** [fredldotme/pVMs#10]
There is no build on the open store for focal on arm64

**Comment by JamiKettunen** [comment]
@fredldotme Ping :)

**Comment by JamiKettunen** [comment]
@ElectrodeYT Why did you close this? I cannot find this in OpenStore app on Fairphone 4 with UT 20.04, https://open-store.io/app/pvms.me.fredl also clearly still has v0.6.2 Focal build missing for `arm64`
![image](https://user-images.githubusercontent.com/47358222/221386728-00c35966-f295-419a-bfcc-b310ba4251c3.png)

**Comment by ElectrodeYT** [comment]
Sorry, just saw the version bump commit and assumed it had been updated

**Comment by fredldotme** [comment]
It's out! Thanks! 🎉
