### ISSUE TITLE
"Display output is not active" and Xorg crashing (Oneplus 6)

### ISSUE THREAD

**Issue by CactiChameleon9** [fredldotme/pVMs#2]
Really cool looking app, thanks for developing it, however I am running into a issue:
Trying to boot the aarch64 fedora 35 iso leads to a message "display output is not active". Trying to boot debian (x86_64) with the graphical installer leads to a Xorg crash loop.

My device is the Oneplus 6.

Thanks in advance for an help.

**Comment by CactiChameleon9** [comment]
![screenshot20211204_190339923](https://user-images.githubusercontent.com/51231053/144721534-3c7a5a81-8b0a-4aaf-940e-485eb0401f53.png)
![screenshot20211204_190419111](https://user-images.githubusercontent.com/51231053/144721536-49753902-76b2-4d89-8f1e-2f9368fc0c69.png)
![screenshot20211204_190308545](https://user-images.githubusercontent.com/51231053/144721537-b0bbd090-a41a-40a7-a179-029047013adb.png)

**Comment by fredldotme** [comment]
"Display output not active" is usually shown during bootup. If it hasn't completed yet it will go on showing that message.
But on the Volla Phone (thanks to KVM) it takes around 3 minutes to get to the desktop.

**Comment by CactiChameleon9** [comment]
I will leave it running and see what happens, thanks for the responce

**Comment by fredldotme** [comment]
I think this can be closed. As the OnePlus 6 is a QCOM device it won't allow use of KVM easily, so that's out-of-scope for this particular device.
